export * from './Slider';
export * from './NewItem';
export * from './BannerHome';
export * from './LoadingData';
export * from './SocialBanner';
export * from './NewsContainer';
export * from './MatchContainer';
export * from './TittleComponent';
export * from './TwitterContainer';